"""modify comments table

Revision ID: 37669e2eebed
Revises: c3b813244844
Create Date: 2020-09-27 16:44:37.347295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37669e2eebed'
down_revision = 'c3b813244844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'comments', ['comment_id'], ['id'])
    op.drop_constraint('comments_blog_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_blog_id_fkey', 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###
