"""modify comments table

Revision ID: 62eaad1f72ec
Revises: 9c3bb7e6fe1d
Create Date: 2020-09-27 17:30:58.469738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62eaad1f72ec'
down_revision = '9c3bb7e6fe1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.Text(), nullable=True))
    op.drop_column('blogs', 'blog_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_post', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
