"""modify comments table

Revision ID: 730f0b3216d9
Revises: 8ad231819918
Create Date: 2020-09-27 16:49:07.088364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730f0b3216d9'
down_revision = '8ad231819918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_comment_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_comment_id_fkey', 'blogs', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
