"""add email column for authentification in users table

Revision ID: 82327478687d
Revises: 1caed7a89ebc
Create Date: 2020-09-26 21:48:50.220317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82327478687d'
down_revision = '1caed7a89ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
