"""modify comments table

Revision ID: db7e04fd9e7e
Revises: 730f0b3216d9
Create Date: 2020-09-27 17:05:05.509718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e04fd9e7e'
down_revision = '730f0b3216d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_content', sa.Text(), nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_content')
    # ### end Alembic commands ###
